spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8086
